Feature/header-nav
alignedcode/acvod-web pull request #1
Opened 2020-09-15 18:17 UTC by kuzkov

Added basic markup

2020-09-16 14:36 UTC, marinbonibon commented on src/app/navbar/navbar.component.html
> +	<ul class="navbar-nav">
Please, change class names according BEM

2020-09-16 14:39 UTC, marinbonibon commented on src/app/tv-shows/tv-shows.component.ts
> +  selector: 'app-tv-shows',
Usually in out projects we don't use prefix app

2020-09-16 14:50 UTC, marinbonibon commented on src/app/navbar/navbar.component.html
> +			<img class="search-icon" src="../../assets/images/search-icon.svg" alt="aeaaeaea">
Interesting alt description =)
And It's better not to use img tag (If you drag this image, you'll see that it will move)

2020-09-18 08:57 UTC, avmaxim requested changes
@kuzkov Much better! A few comments to fix and we're good to GO!

2020-09-18 08:57 UTC, avmaxim commented on src/app/movies/movies.component.html
> +<p>movies works!</p>
))))
You know what to do with this)

2020-09-18 08:57 UTC, avmaxim commented on src/app/navbar/navbar.component.html
> +	<ul class="navbar__list">
Wow - let's use spaces instead of tabs to avoid such layouts like this
![image](https://user-images.githubusercontent.com/9191544/93577722-12e2e080-f9a5-11ea-82a9-18025740e166.png)

2020-09-18 08:57 UTC, avmaxim commented on src/app/navbar/navbar.component.scss
> +		&::placeholder {
As I remember it works badly as a cross-browser solution

2020-09-18 08:57 UTC, avmaxim commented on src/styles/_vars.scss
> +$white: #fff;
Improvement )))))) Actually looks cleaner)

2020-09-18 08:57 UTC, avmaxim commented on src/app/tv-shows/tv-shows.component.ts
> +  selector: 'app-tv-shows',
++

2020-09-18 10:12 UTC, kuzkov commented on src/app/movies/movies.component.html
> +<p>movies works!</p>
do i?

2020-09-18 10:13 UTC, kuzkov commented on src/app/navbar/navbar.component.scss
> +		&::placeholder {
What exactly?

2020-09-18 10:19 UTC, kuzkov commented on src/app/navbar/navbar.component.scss
> +		&::placeholder {
I've also used :not pseudo-class in this stylesheet as I remember

2020-09-24 16:11 UTC, merged