Serge
alignedcode/acvod-web pull request #13
Opened 2020-09-17 11:48 UTC by Sergej-Karyuhin

2020-09-17 16:40 UTC, marinbonibon commented on src/app/fast-search/fast-search.component.scss
> +  .fast-search__title {
If you write styles like this, you don't need to repeat the main class name

2020-09-17 16:40 UTC, marinbonibon commented on src/app/fast-search/fast-search.component.html
> +      <p class="item__title">{{item.name}}</p>
it can be a separate component

2020-09-17 16:40 UTC, marinbonibon commented on src/app/movies-of-the-categories/movies-of-the-categories.component.ts
> +    movies[e.target.attributes.id.value].fullDescription = true;
Don't mutate your movies objects

2020-09-17 16:40 UTC, marinbonibon commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +          <button type="button" name="button" style="margin-right: 10px;">No duplication button Play</button>
Inline styles? And interesting name for your button)

2020-09-17 16:40 UTC, marinbonibon commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +            <img src="https://cdn.iconscout.com/icon/free/png-256/star-bookmark-favorite-shape-rank-like-32386.png" alt="star" width="16px" height="16px">
Think about using something else instead of img

2020-09-17 16:40 UTC, marinbonibon commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +          <button class="category-buttons__button">Adventure</button>
I'm not sure that these are buttons

2020-09-17 16:40 UTC, marinbonibon commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +        <div [ngClass]="{hidden: !movies[i].fullDescription || isHidden}"
Maybe there is some not so complex solution?

2020-09-18 08:25 UTC, closed without merging

2020-09-18 08:46 UTC, avmaxim requested changes
@Sergej-Karyuhin Not bad for the 1st time of PR ;) Please pay attention to my comments and fix it

2020-09-18 08:46 UTC, avmaxim commented on src/app/app.module.ts
> +    MoviesOfTheCategoriesComponent
++ Avoid English articles and "of" everywhere where possible in the code. They pollute it tremendously.

2020-09-18 08:46 UTC, avmaxim commented on src/app/app.module.ts
> +    MoviesOfTheCategoriesComponent
The fewer words the better. Just compare - what looks and reads better - this 
`CategoriesOfTheFilmsComponent`
OR this
`FilmCategoriesComponent`

2020-09-18 08:46 UTC, avmaxim commented on src/app/app.component.scss
> +        @extend %link;
Just remove these styles if they are not used in the porject. Having Extra code is a bad practise

2020-09-18 08:46 UTC, avmaxim commented on src/app/app-routing.ts
> +  // {
Commenting code is not good and it's a temporary solution. Think over using routes instead ;)

2020-09-18 08:46 UTC, avmaxim commented on src/app/categories-of-the-films/categories-of-the-films.component.html
> +<div *ngFor="let category of categories">
Just notice how big file name can be if we use "articles" and "of". 
![image](https://user-images.githubusercontent.com/9191544/93575173-fabd9200-f9a1-11ea-9292-536086034c36.png)
Also learn `section` of HTML5 it's a good way to use it here

2020-09-18 08:46 UTC, avmaxim commented on src/app/categories-of-the-films/categories-of-the-films.component.html
> +  <p class="category-title">{{category.name}}</p>
Paragraph is a block component. But title of the film is inline, so please have a look at the differences in inline and block elements and tags and let's use span here instead. Would you agree?

2020-09-18 08:46 UTC, avmaxim commented on src/app/categories-of-the-films/categories-of-the-films.component.html
> +  <p class="category-title">{{category.name}}</p>
Plus use BEM please over the whole project ;)

2020-09-18 08:46 UTC, avmaxim commented on src/app/categories-of-the-films/categories-of-the-films.component.html
> +  <app-movies-of-the-categories></app-movies-of-the-categories>
Let's avoid "app" prefixes, they pollute the code...

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.html
> +  <p class="fast-search__title">Open all Results</p>
Same for the `<p>`, it's a block here. Do we need block or inline here?

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.html
> +<div class="fast-search">
Same for the section as above

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.html
> +  <div *ngFor="let item of fast_search" class="fast-search__item">
Let's avoid using PHP-like naming conventions and use Google standards. In this case all fields are to be written in camelCase like "fastSearch" + add what exactly you're interating over. It's not clear why for loop interates over fastSearch right? It interates over items of the fast search. Thus let's name it like this - "searchItems"

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.html
> +    <div class="example-img">EXAMPLE IMG</div>
Exactly! This entity is being used in many places. Let's consider to put it to the separate component

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.html
> +    <div class="example-img">EXAMPLE IMG</div>
Let's put images and titles of the movies to the mock file as well

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.scss
> +  .fast-search__title {
Absollutely! Refresh your memory on using & here. It will make the code cleaner

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.component.scss
> +.example-img {
Same here above. It's better to avoid nesting without "&"

2020-09-18 08:46 UTC, avmaxim commented on src/app/fast-search/fast-search.ts
> +    img: 'url'
To make it even more real, you can specify different description and image urls

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +<div class="category-list">
Same for the section here

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +  <div *ngFor="let movie of movies; index as i">
What's the purpose of using index here? As I see we can use `movie` object everywhere instead. Isn't it?

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +            <p class="imdb__title">IMDb 8,5</p>
It's better to put ratings, imgUrl, etc to the mocks files as well to ease up integration with backend later on

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +          <button type="button" name="button" style="margin-right: 10px;">No duplication button Play</button>
Let's avoid React-like shallow DOM inline stylings everywhere since it can lead to side effects

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +</div>
Too many divs everywhere. Let's consider how to make this count smaller

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.scss
> +    -o-transform: scale(1);
As I said at our one meeting, all these prefixes are a good choice for a mixin.

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.scss
> +    -o-transform: scale(1);
And you can notice that we already have such a mixin out there

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.scss
> +    -moz-transition: all 0.7s ease-out;
As I said at our one meeting, all these prefixes are a good choice for a mixin.
And you can notice that we already have such a mixin out there

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.scss
> +.hidden {
Please use "&" to make it more readable and less error-prone

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.scss
> +        color: #FFFFFF;
Let's put general reusable colors to the variables. White is already up there adn can be re-used

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.ts
> +    movies[e.target.attributes.id.value].fullDescription = true;
Yeah, it's a bad practice. Let's think about another option

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies.ts
> +  {
It's a hardcode man ;) Let's avoid it and think another more clean solution

2020-09-18 08:46 UTC, avmaxim commented on src/styles/_general.scss
> +  // overflow: hidden;
Avoid commenting code please. If you see it is not being used, just remove it ;)

2020-09-18 08:46 UTC, avmaxim commented on src/app/movies-of-the-categories/movies-of-the-categories.component.html
> +        <div [ngClass]="{hidden: !movies[i].fullDescription || isHidden}"
Let's make the code above more cleaner