Bugfix/video player
alignedcode/acvod-web pull request #130
Opened 2020-11-05 10:22 UTC by IvanSkadorva

2020-11-06 10:18 UTC, Vladissqq requested changes

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/progress-bar/progress-bar.component.scss
> +    transition: all 0.4s ease 0s;
same code

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-controllers/fullscreen-btn/fullscreen-btn.component.html
> +<div class="fullscreen-btn" (click)="toggleFullscreen()">
why you use name container for div in choose-season.component , but here u use fulscreen-btn ?

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-controllers/fullscreen-btn/fullscreen-btn.component.ts
> +  ngOnDestroy() {
: void?

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-controllers/video-controllers.component.scss
>    &__btns {
i donnt like this class name. Can u change on more accurate class name?

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-controllers/video-controllers.component.ts
where is toggleFullscreen now?

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-controllers/video-settings/video-settings.component.html
> +  <div class="video-settings__btn-container" (click)="toggleContent()">
same problem, read more about BEM

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-player.component.ts
> +      ),
i think all this code u can split on independent functions, and declare them like methods of class

2020-11-06 10:18 UTC, Vladissqq commented on src/app/pages/video-player/video-player.component.ts
> +    // }, 3000);
uncomment or delete)

2020-11-06 13:44 UTC, IvanSkadorva commented on src/app/pages/video-player/video-controllers/video-controllers.component.ts
In the separate component

2020-11-06 13:45 UTC, IvanSkadorva commented on src/app/pages/video-player/video-controllers/video-settings/video-settings.component.html
> +  <div class="video-settings__btn-container" (click)="toggleContent()">
Okay!

2020-11-06 13:55 UTC, IvanSkadorva commented on src/app/pages/video-player/video-controllers/video-controllers.component.scss
>    &__btns {
Hmm, &__btns-bar
Is it good?

2020-11-06 13:56 UTC, IvanSkadorva commented on src/app/pages/video-player/video-controllers/fullscreen-btn/fullscreen-btn.component.html
> +<div class="fullscreen-btn" (click)="toggleFullscreen()">
Thank you, I'll fix it)

2020-11-06 14:25 UTC, Vladissqq submitted a review, later dismissed

2020-11-06 14:25 UTC, Vladissqq commented on src/app/components/choose-season/choose-season.component.html
> +></setting-btn>
i mean here btn-container it is block and btn it is element, className for this btn - btn-container__btn. but for div i think better use setting-btn-container or something like that

2020-11-09 07:34 UTC, Vladissqq approved these changes

2020-11-09 07:34 UTC, merged