Feature/proxy
alignedcode/acvod-web pull request #169
Opened 2020-11-21 11:55 UTC by kuzkov

2020-11-23 06:21 UTC, avmaxim requested changes
Good job! Plz, make sure everyone in our AC VoD team has access to our Heroku server. And plz make me an admin to be able to manage this stuff. Thanks!

2020-11-23 06:21 UTC, avmaxim commented on src/app/shared/services/tv-shows.service.ts
> +            .get(`api/v1/tv/${tvId}/season/${season.seasonNumber + 1 - 1}`)
@kuzkov What is this expression `-1 + 1` equal to in math? :)

2020-11-23 07:05 UTC, Yarrow228 commented on src/app/shared/services/tv-shows.service.ts
> +            .get(`api/v1/tv/${tvId}/season/${season.seasonNumber + 1 - 1}`)
@avmaxim That's because of strange season request, to get next season we shuold pass number of current instead of 'current season number + 1'. 
Alredy deleted this.

2020-11-23 14:33 UTC, marinbonibon commented on src/app/shared/services/movies.service.ts
> +    return this.http.get(`api/v1/movie/${movieId}/similar`);
a lot of places where you've changed a variable to magic string, was not it easier to change this variable in one place and all links would change instead of changing it in all places by hands?

2020-11-24 09:40 UTC, kuzkov commented on src/app/shared/services/movies.service.ts
> +    return this.http.get(`api/v1/movie/${movieId}/similar`);
@marinbonibon 
Nah

2020-11-24 09:53 UTC, marinbonibon approved these changes

2020-11-24 10:31 UTC, marinbonibon approved these changes

2020-11-24 14:36 UTC, avmaxim commented on proxy.config.json
> +  }
@Sergej-Karyuhin check out how Artem solved CORS problem. You can talk to him about this today or we can do it tmrw with you too

2020-11-24 14:36 UTC, avmaxim approved these changes

2020-11-24 14:37 UTC, merged