Ivan skadorva
alignedcode/acvod-web pull request #4
Opened 2020-09-16 06:54 UTC by IvanSkadorva

Created the footer component

2020-09-16 14:57 UTC, marinbonibon commented on src/app/footer/footer.component.html
> +        <div class="container__footer">
Think about class names, bro =)

2020-09-16 15:02 UTC, marinbonibon commented on src/app/footer/footer.component.html
> +                </ul>
It's redundant, you may make it easier

2020-09-16 15:02 UTC, marinbonibon commented on src/app/footer/footer.component.html
> +              <h1>BROWSE</h1>
Is the word 'Browse' the most important word on your page?

2020-09-16 15:06 UTC, marinbonibon commented on src/app/footer/footer.component.scss
> +  font-family: SF Pro Display;
Start with the font you want, and always end with a generic family, to let the browser pick a similar font in the generic family, if no other fonts are available.

2020-09-18 08:48 UTC, avmaxim requested changes
@IvanSkadorva Подпулить дев забыл) Пока не смотрю твой ПР) Как подольешь - маякни)

2020-09-18 09:53 UTC, closed without merging