Feature/film info
alignedcode/acvod-web pull request #8
Opened 2020-09-16 16:41 UTC by Yarrow228

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.html
> +        </div>
I think it's redundant to use 3 containers and paragraphs here

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.html
> +        <p class="info">{{ film.year + ' | ' + film.age_constraint + '+'}}</p>
What can you use instead of p?

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.html
> +        <p class="info">{{ film.year + ' | ' + film.age_constraint + '+'}}</p>
And here we have magic string

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.html
> +          <img src="assets/images/rate-star.png">
It's better not to use img tag (If you drag this image, you'll see that it will move), and I mean all img in this PR

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.html
> +      </div>
Think about another solution

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.scss
> +  font-family: "SF Pro Display";
Start with the font you want, and always end with a generic family, to let the browser pick a similar font in the generic family, if no other fonts are available.
And also you should have variable for the main font

2020-09-17 16:17 UTC, marinbonibon commented on src/app/film-description/film-description.component.scss
> +  font-family: SF Pro Text;
the same about font

2020-09-17 16:23 UTC, Yarrow228 commented on src/app/film-description/film-description.component.html
> +        <p class="info">{{ film.year + ' | ' + film.age_constraint + '+'}}</p>
Maybe span?
Magic string?

2020-09-18 07:55 UTC, avmaxim requested changes
@Yarrow228 Good job for the 1st round of review! Please see our comments to the code below ;) Lt's fix them before merging

2020-09-18 07:55 UTC, avmaxim commented on src/app/app.component.scss
>  :host {
Agree with Marina. No need to include styles not related to the project

2020-09-18 07:55 UTC, avmaxim commented on src/app/app.component.scss
> +
Just remove everything inside this styles file

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +<div class="container">
++ A good practice is to use a more semantical name like "film-description" or smth like that. DIV already means that it's the container, so naming it like "container" is an extra work

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +        </div>
++ The less code the better. If you can omit some tags or merge them - do it. Think how to leave only one out of these 3 tags here

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +        <p class="info">{{ film.year + ' | ' + film.age_constraint + '+'}}</p>
Exactly! Read about inline and block elements. P is a paragraph and it's not actually a good use-case to have it like this. For rendering, labels use span or other inline elements. Read about semantic html and HTML5 tags

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +<div class="container">
++ You can use `<section> `or `<article>` (read the docs and choose the one) to be HTML5 follower.

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +      </div>
++ It's a hardcode @Yarrow228 Brainstorm how we can do it more flexible and reliable.

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +      </div>
I haven't seen any BEM standard over the styles of the PR. Please use BEM to make it look more readable and supportable

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.scss
> +  font-family: "SF Pro Display";
++ Font is basicalyy reusable across all pages, so you better off thinking about putting it to the variable instead of hardcoding it as a magic string

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.scss
> +}
Rewrite this file to use nesting via **_"&"_** instead of **_"A B"_** relation

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.scss
> +}
++ use BEM

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.scss
> +    width: 50px; /* computed */
What's the computed mean here?)

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.scss
> +    font-family: "SF Pro Display";
Same here for the font. It's a magic string. Just imagine if the designer says that he wants to replace this font with another one. In how many places will you be supposted to change it? 20 files? 50? more?)

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/films.ts
> +    title: 'If Beale Street Could Talk',
Don't forget about IDs. Each film or another entity has to contain ID in it to identify and differentiate them

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +          <p>{{ "IMDb" + " " + film.rate}}</p>
Learn template strings and prefer it over this` "" + "" + "" `

2020-09-18 07:55 UTC, avmaxim commented on src/app/film-description/film-description.component.html
> +        <p class="info">{{ film.year + ' | ' + film.age_constraint + '+'}}</p>
Learn template strings and prefer it over this `"" + "" + ""`

2020-09-22 07:43 UTC, Semenone commented on src/app/film-description/film-description.component.html
> +    <span class="info__rate"><span>IMDb {{ film.rate }}</span><span class="info__rate-icon"></span></span>
Do you use BEM or some other approach to class naming? Here it looks like they are used differently or just incorrectly.(film-description and info-text)

2020-09-22 07:43 UTC, Semenone commented on src/app/film-description/film-description.component.html
> +  </div>
class - buttons) bad naming()

2020-09-22 07:43 UTC, Semenone commented on src/app/film-description/film-description.component.scss
> +  border-radius: 9px;
In ideal project you css properties positioned the same way, position, then dimensions, and so on

2020-09-22 07:43 UTC, Semenone commented on src/app/film-description/film-description.component.ts
> +import { films } from "./films";
If you using single quotes in imports, you will use their everywhere...

2020-09-22 07:43 UTC, Semenone commented on src/app/film-description/film-description.component.ts
> +  film_index:number = 1;/* Got from slider? */
The type is usually preceded by a space after the colon

2020-09-24 06:15 UTC, Semenone commented on src/app/film-description/film-description.component.html
> +<article class="film-info">
Refactored) bad name for commit. What you refactor?

2020-09-24 16:41 UTC, merged