Feature/all search results
alignedcode/acvod-web pull request #80
Opened 2020-10-12 11:51 UTC by Sergej-Karyuhin

[ACVOD-61]

2020-10-12 14:32 UTC, Vladissqq commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.ts
> +  toggleIcon() {
use private public declaration

2020-10-12 14:32 UTC, Vladissqq commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.ts
> +    this.clicked = !this.clicked;
this.clicked != this.clicked;

2020-10-12 14:32 UTC, Vladissqq commented on src/app/pages/video-player/video-settings/video-settings.component.scss
> +  margin-left: -238px; // CHANGE IT!
Are you changed it ?

2020-10-12 14:32 UTC, Vladissqq commented on src/app/shared/components/genres/genres.component.html
> +  <div *ngFor="let genre of genres" class="genres__item">
Do you use it somewhere ?

2020-10-13 07:56 UTC, marinbonibon requested changes

2020-10-13 07:56 UTC, marinbonibon commented on src/app/components/search-result-item/search-result-item.component.html
> +    <div class="result__text-container">
Maybe it would be better to use here more specific word like info instead of just text

2020-10-13 07:56 UTC, marinbonibon commented on src/app/app-routing.ts
> +    component: AllSearchResultsComponent,
If you have partial search results, it's ok, if you don't, I think word all is redundant

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/pages.module.ts
> +import { WatchListButtonComponent } from '../shared/components/watch-list-button/watch-list-button.component';
Instead of this you can just import shared module and use its components

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.scss
> +  border-width: 0px 0 0px 30px;
why in some cases there is 0px and in other just 0?

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.html
> +<button class="play-pause-button" (click)="playPauseVideo()" (click)="toggleIcon()" [ngClass]="{
I think you may call toggleIcon method in playPauseVideo method

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.html
> +    'play': !clicked
And here ternary operator

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.html
> +        {{ videoDuration * 1000 | date: 'H:mm:ss':'UTC' }}
1000 is a magic number

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.html
> +        <play-pause-btn [videoplayer]="videoplayer" class="video-player__play-button"></play-pause-btn>
Do you use this button in many places? Why do you need to make it a separate component?

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.scss
> +    margin: 8px 11px 8px 11px;
it can be shorter

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/video-settings/video-settings.component.scss
> +    margin: 8px 11px 8px 11px;
the same as previous comment

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/video-settings/video-settings.component.scss
> +  margin-left: -238px; // CHANGE IT!
Negative margins are bad practice

2020-10-13 07:56 UTC, marinbonibon commented on src/app/shared/components/search-input/search-input.component.scss
> +      padding-left: 48px;
Why don't write in one line like before?

2020-10-13 07:56 UTC, marinbonibon commented on src/app/pages/video-player/play-pause-btn/play-pause-btn.component.ts
> +  playPauseVideo(event: any) {
Please, write type for returned value, and if method doesn't return anything, that its type is void

2020-10-13 11:40 UTC, closed without merging