Hotfix/clickable video player
alignedcode/acvod-web pull request #87
Opened 2020-10-15 10:50 UTC by IvanSkadorva

2020-10-15 14:59 UTC, kuzkov commented
I don't think that using native progress element is a good idea. Custom implementation of progress bar could be more flexible and customizable than progress element.

2020-10-15 15:07 UTC, kuzkov commented
![image](https://user-images.githubusercontent.com/58119305/96148063-934b2180-0f10-11eb-98f3-2435320d368d.png)
Media queries can be nested

2020-10-15 15:16 UTC, kuzkov requested changes
![image](https://user-images.githubusercontent.com/58119305/96149864-79124300-0f12-11eb-998d-71d3d1412a5a.png)
I don't think that's good)))

2020-10-15 15:16 UTC, kuzkov commented on src/app/pages/video-player/progress-bar/progress-bar.component.scss
>  }
Media queries can be nested

2020-10-16 06:58 UTC, IvanSkadorva commented on src/app/pages/video-player/progress-bar/progress-bar.component.scss
>  }
fixed

2020-10-16 13:06 UTC, merged