Hotfix/fullscreen
alignedcode/acvod-web pull request #90
Opened 2020-10-16 16:30 UTC by IvanSkadorva

2020-10-20 10:51 UTC, marinbonibon requested changes

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-end-screen/video-end-screen.component.html
>  <div class="end-screen">
Maybe think about another class name? Because I don't understand what you wanted to say by "конец экрана")

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-end-screen/video-end-screen.component.ts
>    @Input() nextVideo;
Miss type

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.ts
>    selector: 'app-video-player',
I thought you removed prefix app from project

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.ts
>    isMouseMove: boolean = false;
access modifiers again, check them in all components, please

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-player/video-player.component.ts
>      this.nextVideo = this.moviesService.getRandMovieExceptThis(this.id).pipe();
Why do you need pipe method without operators?

2020-10-20 10:51 UTC, marinbonibon commented on src/app/services/video-player.service.ts
> +      ? docWithBrowsersExitFunctions.msExitFullscreen()
this and next methods are hard to read, try to refactor

2020-10-20 10:51 UTC, marinbonibon commented on src/app/pages/video-player/video-dropdown-info/video-back-button/video-back-button.component.ts
> +    this.videoPlayerService.isFullscreen$.subscribe((isFullscreen) => {
As I understood back button only close the full screen, and if I want to close the player, what should I do?
And why this button in in video-dropdown-info folder if you use it not only here?

2020-10-21 05:00 UTC, IvanSkadorva commented on src/app/pages/video-player/video-player/video-player.component.ts
>    selector: 'app-video-player',
Indeed, I missed this selector. Thank you

2020-10-21 05:10 UTC, IvanSkadorva commented on src/app/pages/video-player/video-player/video-player.component.ts
>      this.nextVideo = this.moviesService.getRandMovieExceptThis(this.id).pipe();
This is a question for Yaroslav

2020-10-25 16:51 UTC, merged